// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7BrK4eZEV0ld7zS_R0IGoL9BFig02oic',
    appId: '1:620340816204:web:7e5e76f70f0ca570a0c7e9',
    messagingSenderId: '620340816204',
    projectId: 'flutapp-eafa6',
    authDomain: 'flutapp-eafa6.firebaseapp.com',
    storageBucket: 'flutapp-eafa6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4ez_pOT7C0rf9zA_jecXrfEIcteWV2v4',
    appId: '1:620340816204:android:830f361b29dc202ea0c7e9',
    messagingSenderId: '620340816204',
    projectId: 'flutapp-eafa6',
    storageBucket: 'flutapp-eafa6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyx8IQz59bpHHeGh9bQEXNwE_7f_nOPyM',
    appId: '1:620340816204:ios:31d06b1f7f1ad597a0c7e9',
    messagingSenderId: '620340816204',
    projectId: 'flutapp-eafa6',
    storageBucket: 'flutapp-eafa6.firebasestorage.app',
    iosBundleId: 'com.example.Crudapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyx8IQz59bpHHeGh9bQEXNwE_7f_nOPyM',
    appId: '1:620340816204:ios:31d06b1f7f1ad597a0c7e9',
    messagingSenderId: '620340816204',
    projectId: 'flutapp-eafa6',
    storageBucket: 'flutapp-eafa6.firebasestorage.app',
    iosBundleId: 'com.example.Crudapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD7BrK4eZEV0ld7zS_R0IGoL9BFig02oic',
    appId: '1:620340816204:web:428709fede140a0aa0c7e9',
    messagingSenderId: '620340816204',
    projectId: 'flutapp-eafa6',
    authDomain: 'flutapp-eafa6.firebaseapp.com',
    storageBucket: 'flutapp-eafa6.firebasestorage.app',
  );
}
